#!/usr/bin/env bash
# A script to dig a website and display it IP address

array=("www" "lb-01" "web-01" "web-02")

if [ "$2" ]; then
	sub="$2"
	dig "$2"."$1" | grep -A1 'ANSWER SECTION' | grep -v 'ANSWER SECTION' | \
	awk -v dom="$sub" '{ print "The subdomain " dom " is a " $4 " record and points to " $5 }'
else
    for sub in "${array[@]}"; do
		dig "$sub"."$1" | grep -A1 'ANSWER SECTION' | grep -v 'ANSWER SECTION' | \
		awk -v dom="$sub" '{ print "The subdomain " dom " is a " $4 " record and points to " $5 }'
	done
fi
