#!/usr/bin/env bash
# a script to install nginx and set it up
apt update
apt -y upgrade
apt-get -y install nginx
apt-get -y install ufw
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.html
