#!/usr/bin/env bash
# a script to install nginx and set it up
apt-get -y install nginx
ufw allow 'Nginx HTTP'
systemctl start nginx
systemctl enable nginx
echo 'Hello World!' > /var/www/html/index.html
