#!/usr/bin/env bash
# a script to install nginx and set it up
apt update
apt-get -y install nginx
apt-get -y install systemctl
apt-get -y install ufw
systemctl start nginx
systemctl enable nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/redirect_ne
redirect="\n\n\tlocation /redirect_me {\n\t\treturn 301 index.html;\n\t}"
sed -i "/server_name _;$/a $redirect" /etc/nginx/sites-available/default
sed -i "s/n$/\t/" /etc/nginx/sites-available/default
systemctl restart nginx
