#!/usr/bin/env bash
# A sxript to configure an ubuntu server to redirect a page
sed -i "s/80/8080/" /etc/nginx/sites-available/default
touch /etc/nginx/sites-available/redirect.conf
redirect="if (\$request_filename ~ /var/www/html/redirect_me) {\n\trewrite ^ http://www.google.comm? permanent\n}"
echo -e "$redirect" > /etc/nginx/sites-available/redirect.conf
/etc/init.d/nginx reload
