#!/usr/bin/env bash
# a script to install nginx and set it up
apt update
apt-get -y install nginx
apt-get -y install systemctl
apt-get -y install ufw
systemctl start nginx
systemctl enable nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/redirect_ne
redirect="\n\n\tlocation /redirect_me {\n\t\treturn 301 index.html;\n\t}"
sed -i "/server_name _;$/a $redirect" /etc/nginx/sites-available/default
sed -i "s/n$/\t/" /etc/nginx/sites-available/default
mkdir -p /usr/share/nginx/html
echo -e "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
error_404="\n\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t\t}"
sed -i "/server_name _;$/a $error_404" /etc/nginx/sites-available/default
sed -i "/^n$/d" /etc/nginx/sites-available/default
systemctl restart nginx
