#!/usr/bin/env bash
# a script to install nginx and set it up
apt update
apt-get -y install nginx
apt-get -y install systemctl
apt-get -y install ufw
systemctl start nginx
syatemctl enable nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/redirect_ne
redirect="\tlocation /redirect_me {\n\t\treturn 301 www.google.com;\n\t}"
sed -i "/server_name/a $redirect/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/new_404.html
sed -i 's/404/new_404.html/' /etc/nginx/sites-available/default
