#!/usr/bin/env bash
# A script to add a custom header to nginx response
new_header="\n\n\t\tadd_header X-Served-By $(hostname);"
sed -i "/location/a $new_header" /etc/nginx/sites-available/default
sed -i "/^n$/d" /etc/nginx/sites-available/default
systemctl restart nginx
