#!/usr/bin/env bash
# a script to print superstitious umbers up to 20

a=1

while [ "$a" -le 20 ]; do
    case $a in    
    4)
        echo $a
        echo bad luck from China
        ;;
    9)
        echo $a
        echo bad luck from Japan
        ;;
    17)
        echo $a
        echo bad luck from Italy
        ;;
    *)
        echo $a
        ;;
    esac
    ((a+=1))
done
