#!/usr/bin/env bash
# a script to display the clock

a=0

while [ "$a" -le 12 ]; do

    echo Hour: $a
    
    b=1
    
    while [ "$b" -le 59 ]; do
        echo $b
        ((b+=1))
    done
    ((a+=1))

done
