#!/usr/bin/env bash
#A script to trap kill cdommands and execute them
trap 'echo I hate the kill command; rm /var/run/myscript.pid; exit' SIGTERM
trap 'echo Y U no love me?!; exit' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT

A=0
echo $$ > /var/run/myscript.pid
while [ $A -le 1 ]; do
  echo To infinity and beyond
  sleep 1
done
