#!/usr/bin/env bash
# A file to open the /etc/passwd file for reading and writing about it
while IFS=: read -r username password gid home_dir shell comment uid
do
    echo "The user $username is part of the $gid gang, lives in $home_dir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $comment"
done < /etc/passwd

