#!/usr/bin/env bash
# A file to open the /etc/passwd file for reading and writing about it
while IFS=: read -r username password gid comment home_dir shell
do
    # Display the user information in the specified format
    echo "The user $username is part of the $gid gang, lives in $home_dir and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: $comment"
done < /etc/passwd

