#!/usr/bin/env bash
# a script that prints Hi on the 9th iteration

a=1

while [ "$a" -le 10 ]; do
    if [ "$a" -eq 9 ]; then
        echo Hi
        ((a+=1))
        continue
    else
        echo Best School
        ((a+=1))
    fi
done
