#!/usr/bin/env bash
# To remove - from file names
# Set the Internal Field Separator (IFS) to a newline
IFS=$'\n'

# Loop over all files in the current directory
for file in ./*; do
    # Extract the part of the filename after the first dash
    part=$(basename "$file" | cut -d'-' -f2-)
    # Print the part
    echo "$part"
done

