#!/usr/bin/env bash
# A script to change ip address
touch hosts.new
cp /etc/hosts hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' hosts.new
sed -i '$ a 8.8.8.8	facebook.com' hosts.new
cp -f hosts.new /etc/hosts
