#!/usr/bin/env bash
# A script to change ip address
cp /etc/hosts ~/hosts.new
sed '/localhost/s/127.0.0.1/127.0.0.2/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
echo '8.8.8.8	facebook.com' | tee -a /etc/hosts
