#!/usr/bin/env bash
# A script to change ip address

sudo cp /etc/hosts /etc/hosts.new

sudo cut -f 1 /etc/hosts

echo '127.0.0.2	localhost' | sudo tee -a /etc/hosts
echo '8.8.8.8	facebook.com' | sudo tee -a /etc/hosts
